DROP TABLE IF EXISTS `batch_job`;

CREATE TABLE `batch_job`(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    group_name VARCHAR(20) NOT NULL,
    job_name VARCHAR(20) DEFAULT '',
    job_class VARCHAR(200) NOT NULL,
    job_cron VARCHAR(30) NOT NULL DEFAULT 0,
    job_params VARCHAR(200) DEFAULT '',
    job_status INT NOT NULL DEFAULT 0,
    created_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);