DROP TABLE IF EXISTS `forum`;

CREATE TABLE `forum`(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500),
    content VARCHAR(500) NOT NULL,
    user_id INT NOT NULL,
    created_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
    
  